### ISSUE TITLE
Broken link for UN/CEFACT Common Codes

### ISSUE THREAD

**Issue by konstantinosGombakis** [smart-data-models/dataModel.Energy#10]
The link for the  UN/CEFACT Common Codes website [http://wiki.goodrelations-vocabulary.org/Documentation/UN/CEFACT_Common_Codes](http://wiki.goodrelations-vocabulary.org/Documentation/UN/CEFACT_Common_Codes) seems to be broken

**Comment by albertoabellagarcia** [comment]
Now it looks to be working. Maybe it was a temporal issue?

**Comment by konstantinosGombakis** [comment]
No is still down.
[https://www.isitdownrightnow.com/wiki.goodrelations-vocabulary.org.html](https://www.isitdownrightnow.com/wiki.goodrelations-vocabulary.org.html)

**Comment by bobeal** [comment]
It is only available in http (not https). maybe it explains why it is seen as down.

**Comment by albertoabellagarcia** [comment]
All the links we have are with http so it is up.
