### ISSUE TITLE
model.yaml for ThreePhaseAcMeasurement has inverted values for xngsi properties of reactiveEnergyImport

### ISSUE THREAD

**Issue by isalvadori** [smart-data-models/dataModel.Energy#7]
Hi, 
I noticed that in the `model.yaml` for `ThreePhaseAcMeasurement` (https://github.com/smart-data-models/dataModel.Energy/blob/master/ThreePhaseAcMeasurement/model.yaml), the attributes `model` and `units` of the `x-ngsi` attribute of the `reactiveEnergyInput` are reversed.

```x-ngsi:
        model: 'kilovolt-ampere-reactive-hour (kVArh)'
        type: Property
        units: http://schema.org/StructuredValue
```

**Comment by albertoabellagarcia** [comment]
you are right. 
I am reviewing the code to fix it.

**Comment by albertoabellagarcia** [comment]
It is not the code (it is the original schema, which is misplacing the units and the model).
fixed and updating the model. 
thanks
