### ISSUE TITLE
Additional bracket in model attribute of phaseToPhaseVoltage in ThreePhaseAcMeasurement

### ISSUE THREAD

**Issue by isalvadori** [smart-data-models/dataModel.Energy#8]
Hi, 
in the model attribute of `phaseToPhaseVoltage` of `ThreePhaseAcMeasurement` model (https://github.com/smart-data-models/dataModel.Energy/blob/master/ThreePhaseAcMeasurement/model.yaml) there is an additional bracket.

```
x-ngsi:
        model: (http://schema.org/StructuredValue
```
It's not a big deal, but if someone is trying to extract the information about the model it could be a bit annoying to deal with.

**Comment by albertoabellagarcia** [comment]
You are right, bear in mind that the model.yaml is generated automatically, so the error origin was the schema.org. fixed.
In few minutes update all documentation to version 0.0.3
thanks
