### ISSUE TITLE
Missing L3 from several properties

### ISSUE THREAD

**Issue by konstantinosGombakis** [smart-data-models/dataModel.Energy#9]
The following [properties](https://github.com/smart-data-models/dataModel.Energy/blob/0483588aa1e244a3ab9743d61ab7655f8475454f/ACMeasurement/doc/spec.md#list-of-properties)
- activeEnergyExport
- activeEnergyImport
- activePower
- apparentEnergyExport
- .....
on the [spec.md](https://github.com/smart-data-models/dataModel.Energy/blob/master/ACMeasurement/doc/spec.md) are missing L3, the definition of the third phase. They only display L1, L2. 
They have correct definition on the  [yaml representation](https://github.com/smart-data-models/dataModel.Energy/blob/master/ACMeasurement/doc/spec.md#data-model-description-of-properties)
- L1
- L2
- L3

**Comment by albertoabellagarcia** [comment]
Thanks, It has been corrected
